#!/usb/bin/env sh

start_xvfb() {
	Xvfb $DISPLAY -screen 0 $XVFB_RESOLUTION &
	x11vnc -passwd $VNC_PASSWORD -display $DISPLAY -noxdamage &
}

start_x() {
	startx -- $DISPLAY &
}

if [ -z "$VNC_PASSWORD" ]; then
	echo "starting x"
	start_x
else
	echo "starting xvfb"
	start_xvfb
fi

metacity &
dbus-daemon --fork --session --address $DBUS_SESSION_BUS_ADDRESS
/usr/src/app/node_modules/.bin/electron --no-sandbox -r /usr/lib/balena-electronjs /usr/src/app
