#!/usb/bin/env sh

if [ -n "$USE_XVFB" ]; then
	echo "starting xvfb"
	Xvfb $DISPLAY -screen 0 $XVFB_RESOLUTION &
else
	echo "starting x"
	startx -- $DISPLAY &
fi

if [ -n "$VNC_PASSWORD" ]; then
	x11vnc -passwd $VNC_PASSWORD -display $DISPLAY -noxdamage &
fi

metacity &
dbus-daemon --fork --session --address $DBUS_SESSION_BUS_ADDRESS
/usr/src/app/node_modules/.bin/electron --no-sandbox -r /usr/lib/balena-electronjs /usr/src/app
