export BALENAELECTRONJS_OVERLAY_DELAY=500
export ELECTRON_ENABLE_LOGGING=1
export BALENAELECTRONJS_SETTINGS_BUTTON_POSITION=150,13
export BALENAELECTRONJS_MOUNTS_BUTTON_POSITION=200,13
export BALENAELECTRONJS_SLEEP_BUTTON_POSITION=20,13
export BALENAELECTRONJS_WIFI_BUTTON_POSITION=114,13
export BALENAELECTRONJS_ZOOM_FACTOR=1.5
./node_modules/.bin/electron -r .. index.js
